### ISSUE TITLE
client.get applies token incorrectly when query params are present

### ISSUE THREAD

**Issue by heisler3030** [bitpay/ruby-client#39]
Because `client.get` appends `?token=<token>` directly to the passed GET path, this causes issues if query params are already attached, because now there are two ?'s in the string.

Proposed fix:  add logic to substitute & if there is already a ? in the path.

Test case:  

`client.get(path: "ledgers/BTC?startDate=2015-01-01&endDate=2015-02-01" token: token)`

**Comment by philosodad** [comment]
There's a workaround to this problem right now (don't pass the token as an argument, add it to the path) so I'd call this a medium to low priority bug. Might be worth fixing when we fix the other bug.

**Comment by heisler3030** [comment]
Proposed fix: https://github.com/bitpay/ruby-client/pull/41

**Comment by heisler3030** [comment]
Fixed with merge as above
