### ISSUE TITLE
GET /ledgers breaks client.get

### ISSUE THREAD

**Issue by heisler3030** [bitpay/ruby-client#40]
Because the `/ledgers` endpoint does not return an encapsulating `data` node in the json response, it breaks our assumption and causes a `TypeError` at runtime.

Test Case:
`client.get(path: "ledgers/BTC?startDate=2015-01-01&endDate=2015-02-01&token=#{client.instance_variable_get(:@tokens)['merchant']}")`

Proposed Fix:  Add if/then logic to include full body if no [data] element is found

**Comment by philosodad** [comment]
This is a fairly easy, high value fix. I recommend the fix is made to 2.3 and 2.4 releases this mission.

**Comment by heisler3030** [comment]
Fix verified using test case above
