### ISSUE TITLE
secp256k1 curve not supported on any fedora based platform

### ISSUE THREAD

**Issue by sylvainsf** [bitpay/ruby-client#47]
SDK is unable to establish any client connections from Fedora/RHEL/CentOS hosts due to the curve used for keys/signing.

**Comment by ionux** [comment]
Working with Bitcoin on Fedora is generally a problem all around due, in part, to it's hobbled OpenSSL binary with really limited (or no) ECC support.  I believe it has something to do with questions concerning ECC patents.  There are some third-party repo's that provide a complete OpenSSL implementation that may work or you could compile your own version of it with the correct crypto support.

**Comment by sylvainsf** [comment]
What about posting to a rest api endpoint requires bitcoin crypto?

**Comment by ionux** [comment]
BitPay's cryptographically-secure API uses the same ECC to create asymmetric keypairs and digital signatures for requests issued to non-public API endpoints.  Without the base crypto support to create these keys and signatures, calling anything other than public endpoints won't work.
